let div = document.getElementById("first");
div.style.backgroundColor = "yellow";
div.style.margin = "20px" ;
div.style.padding = "10px";
div.style.fontSize = "18px";
div.style.fontWeight = "bold";
div.style.height = "200px";
div.style.width = "300px";
div.style.color = " blue";